version: "3.3"
volumes:
   mysql-data:     
services:
   mysql:
     image: mysql:8.0
     restart: on-failure
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
     volumes:
       - mysql-data:/var/lib/mysql

   nginx:
     build:
       context: .
       dockerfile: docker/nginx/Dockerfile
     restart: on-failure
     volumes:
       - './app/public/:/usr/src/app'
       - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
     ports:
       - '${NGINX_PORT}:80'
     depends_on:
       - php

   php:
     build:
       context: .
       dockerfile: docker/php/Dockerfile
     restart: on-failure
     volumes:
       - './app/:/usr/src/app'
     env_file:
       - .env
     user: ${LOCAL_USER}
