version: "3.3"
volumes:
   mysql-data:     
services:
   mysql:
     image: mysql:5.7
     restart: on-failure
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: example
     volumes:
       - mysql-data:/var/lib/mysql

   nginx:
     image: nginx:1.15.3-alpine
     restart: on-failure
     volumes:
       - './app/public/:/usr/src/app'
       - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
     ports:
       - '8080:80'
     depends_on:
       - php

   php:
     build:
       context: .
       dockerfile: docker/php/Dockerfile
     restart: on-failure
     volumes:
       - './app/:/usr/src/app'
     env_file:
       - .env
     user: 1000:1000
